SELECT TOP 5 * FROM customer;

ALTER TABLE customer 
ALTER COLUMN age INT;

ALTER TABLE customer
ALTER COLUMN purchase_amount FLOAT;

ALTER TABLE customer
ALTER COLUMN review_rating FLOAT;

ALTER TABLE customer
ALTER COLUMN previous_purchases INT;

ALTER TABLE customer
ALTER COLUMN purchase_frequency_days INT;


--Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS total_revenue
FROM customer 
GROUP BY gender;


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer);


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5 item_purchased, AVG(review_rating) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC;


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT ROUND(AVG(purchase_amount),2) AS avg_purchase_amt, shipping_type
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;   


--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT COUNT(customer_id) AS total_customers,
	   ROUND(AVG(purchase_amount),2) AS avg_spend, 
	   SUM(purchase_amount) AS total_revenue, 
	   subscription_status
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5 item_purchased,
	   ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1.0
	   ELSE 0.0 END) / COUNT(*), 2) * 100.0 AS perc_of_purchases
FROM customer
GROUP BY item_purchased
ORDER BY perc_of_purchases DESC;


--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
WITH customer_data AS ( 
	SELECT customer_id, previous_purchases,
	CASE WHEN previous_purchases = 1 THEN 'New'
		 WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
		 ELSE 'Loyal'
	END AS customer_segment
	FROM customer
)
SELECT COUNT(customer_id) AS count_count, customer_segment
FROM customer_data
GROUP BY customer_segment;


--Q8. What are the top 3 most purchased products within each category? 
WITH top_purchased_products AS (
	SELECT item_purchased, category, COUNT(customer_id) AS total_count,
	ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
	FROM customer
	GROUP BY item_purchased, category
)
SELECT item_rank, item_purchased, category, total_count
FROM top_purchased_products
WHERE item_rank <= 3;


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id)
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


--Q10. What is the revenue contribution of each age group? 
SELECT SUM(purchase_amount) AS total_revenue, age_groups
FROM customer
GROUP BY age_groups
ORDER BY total_revenue DESC;